"""Summary generation and storage.

Note: This module stores summaries provided by the agent.
LLM-based summary generation is delegated to the calling agent.
"""

import uuid
from datetime import datetime
from pydantic import BaseModel

from storage import Storage, SummaryRecord


class SummaryInput(BaseModel):
    """Input for creating a summary."""
    session_id: str
    task: str
    decisions: list[str]
    pending: list[str]
    key_artifacts: list[str]
    context_for_continue: str


class SummaryResult(BaseModel):
    """Result after creating a summary."""
    summary_id: str
    session_id: str
    created_at: str


class Summarizer:
    """Manages summary creation and retrieval.

    Summaries are generated by the agent and submitted for storage.
    This follows the "agent decides when to summarize" pattern.
    """

    def __init__(self, storage: Storage):
        self.storage = storage

    async def create(self, summary_input: SummaryInput) -> SummaryResult:
        """Store a summary provided by the agent."""
        summary = SummaryRecord(
            summary_id=str(uuid.uuid4()),
            session_id=summary_input.session_id,
            created_at=datetime.utcnow().isoformat(),
            task=summary_input.task,
            decisions=summary_input.decisions,
            pending=summary_input.pending,
            key_artifacts=summary_input.key_artifacts,
            context_for_continue=summary_input.context_for_continue
        )
        await self.storage.save_summary(summary)
        return SummaryResult(
            summary_id=summary.summary_id,
            session_id=summary.session_id,
            created_at=summary.created_at
        )

    async def get(self, session_id: str) -> SummaryRecord | None:
        """Retrieve the most recent summary for a session."""
        return await self.storage.get_summary(session_id)

    async def search(self, query: str, limit: int = 5) -> list[SummaryRecord]:
        """Search summaries by task content.

        Note: This is a simple substring match.
        For semantic search, integrate with a vector store.
        """
        return await self.storage.search_summaries(query, limit)